apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: {{ .Values.notebook_name }}
    app.kubernetes.io/part-of: vtxwb
  name: {{ .Values.s3_proxy_config_pvc }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.s3_proxy_config_pvc_size | default "1Gi" }}
  storageClassName: standard-rwo
