# Author: andybubune@google.com
# tenants.yaml
# Global chart paths (referenced in helmfile.yaml)
---
gdc_buckets_chart_path: "../../charts/gdc-buckets"
gdc_dbs_chart_path: "../../charts/gdc-dbs"
gdc_iam_roles_chart_path: "../../charts/gdc-iam-roles"
gdc_iam_rolebindings_chart_path: "../../charts/gdc-iam-role-bindings"
gdc_projects_chart_path: "../../charts/gdc-projects"
gdc_projects_sa_chart_path: "../../charts/gdc-project-service-accounts"
gdc_vm_chart_path: "../../charts/gdc-vm"

gdc_tenants:
  app-team-1:
    global:
      customroles: []
      iamrolebindings:
        - role: "project-creator"
          subject_kind: "User"
          subject_name: "fop-mellon@example.com"
      projects:
        - name: "mellon-prj"
          iamrolebindings: 
          - role: "project-iam-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "secret-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "namespace-admin"
            subject_kind: "User"
            subject_name: "fop-mellon@example.com"
          - role: "project-bucket-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "project-vm-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "project-networkpolicy-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          serviceaccounts: 
            - "mellon-frontend-sa"
            - "mellon-backendend-sa"
          resources:
            vms:
              - name: "mellon-frontend-vm"
                image_name: "rocky-8-v20250809-gdch"
                image_namespace: "vm-system"
                boot_disk_size: "20Gi"
                machine_type: "n3-standard-2-gdc"
              - name: "mellon-backend-vm"
                image_name: "rocky-8-v20250809-gdch"
                image_namespace: "vm-system"
                boot_disk_size: "20Gi"
                machine_type: "n3-standard-2-gdc"
                ingressEnabled: true
                ssh:
                  uiAccessEnabled: true
                  createProjectNetworkPolicy: true
            buckets:
              - name: "mellon-bucket1"
                description: "test bucket"
                storage_class: "Standard"
                location: "zone1"
        
        # --- SECOND PROJECT (DBs) ---
        - name: "mellon-db-prj"
          iamrolebindings:
          - role: "project-iam-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "secret-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "project-db-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "secret-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          serviceaccounts: 
            - "mellon-pgdb-sa"
            - "mellon-alloydb-sa"
          resources:
            dbs:
              alloydbomni:
                enabled: true
                clusterName: lts-ado-cluster
                version: "15"
                cpu: 2
                memory: 4Gi
                dataDiskSize: 10Gi
                base64EncodedPassword: "WW91clNlY3VyZVBAc3N3MHJk"
              postgresql:
                enabled: true
                clusterName: lts-pg-cluster
                version: "15"
                cpu: 2
                memory: 4Gi
                dataDiskSize: 10Gi
                base64EncodedPassword: "WW91clNlY3VyZVBAc3N3MHJk"
              oracle:
                enabled: false
                clusterName: lts-ora-cluster
                version: "19"
                cpu: 2
                memory: 8Gi
                dataDiskSize: 20Gi
                logDiskSize: 20Gi
                cdbName: LTSORACDB
                base64EncodedPassword: "WW91clNlY3VyZVBAc3N3MHJk"

  app-team-2:
    global:
      customroles: []
      iamrolebindings:
        - role: "project-creator"
          subject_kind: "User"
          subject_name: "fop-glee@example.com"
      projects:
        - name: "glee-prj"
          iamrolebindings: 
          - role: "project-iam-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "secret-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "namespace-admin"
            subject_kind: "User"
            subject_name: "fop-glee@example.com"
          - role: "project-bucket-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "project-vm-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          - role: "project-networkpolicy-admin"
            subject_kind: "User"
            subject_name: "fop-iac@example.com"
          serviceaccounts: 
            - "glee-sa"
          resources:
            vms:
              - name: "glee-vm2"
                image_name: "rocky-8-v20250809-gdch"
                image_namespace: "vm-system"
                boot_disk_size: "20Gi"
                machine_type: "n3-standard-2-gdc"
            buckets:
              - name: "glee-bucket"
                description: "test bucket"
                storage_class: "Standard"
                location: "zone1"
