# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
bases:
  - bases/helmDefaults.yaml.gotmpl
  - bases/environments.yaml.gotmpl

helmfiles:
  - path: releases/0-bootstrap/helmfile.yaml.gotmpl
  - path: releases/0-org-setup/helmfile.yaml.gotmpl
  - path: releases/1-project-factory/helmfile.yaml.gotmpl
  - path: releases/2-resources/helmfile.yaml.gotmpl
  - path: releases/3-clusters/helmfile.yaml.gotmpl
  - path: releases/4-notebooks/helmfile.yaml.gotmpl
  - path: releases/5-patterns/helmfile.yaml.gotmpl



missingFileHandler: Error
