apiVersion: v2
name: gdc-standard-clusters
description: A Helm chart for Google Distributed Cloud standard clusters
type: application
version: 0.1.1
appVersion: "1.26.5"
maintainers:
  - name: gdc-iac
