{{/*
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/ -}}
{{- if .Values.gdc.enabled }}
apiVersion: postgresql.dbadmin.gdc.goog/v1
kind: DBCluster
metadata:
  name: rag-db
  namespace: {{ include "p6-resilient-rag-agent.namespace" . }}
  labels:
    {{- include "p6-resilient-rag-agent.labels" . | nindent 4 }}
spec:
  version: POSTGRESQL_14
  availabilityType: ZONAL_HA
  resources:
    requests:
      cpu: '4'
      memory: 16Gi
  storage:
    size: 100G
---
apiVersion: iam.gdc.goog/v1
kind: ProjectPolicy
metadata:
  name: rag-bindings
  namespace: {{ include "p6-resilient-rag-agent.namespace" . }}
  labels:
    {{- include "p6-resilient-rag-agent.labels" . | nindent 4 }}
spec:
  bindings:
  - role: Role/ai-ocr-developer
    members:
    - serviceAccount:rag-sa
  - role: Role/ai-translation-developer
    members:
    - serviceAccount:rag-sa
{{- end }}
