# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.standardClusters }}
{{- range $key, $value := .Values.standardClusters }}
---
apiVersion: cluster.gdc.goog/v1
kind: Cluster
metadata:
  name: {{ required "A valid .name is required for each cluster" $value.name | quote }}
  namespace: {{ required "A valid .namespace is required for each cluster" $value.namespace | quote }}
spec:
  clusterNetwork:
    podCIDRSize: {{ default 21 $value.podCIDRSize }}
    serviceCIDRSize: {{ default 23 $value.serviceCIDRSize }}
  initialVersion:
    kubernetesVersion: {{ required "A valid .kubernetesVersion is required" $value.kubernetesVersion | quote }}
  nodePools:
{{- range $pool := $value.nodePools }}
  - name: {{ required "A valid nodePool name is required" $pool.name | quote }}
    machineTypeName: {{ required "A valid machineTypeName is required" $pool.machineTypeName | quote }}
    nodeCount: {{ required "A valid nodeCount is required" $pool.nodeCount }}
{{- if $pool.taints }}
    taints:
{{ toYaml $pool.taints | indent 4 }}
{{- end }}
{{- if $pool.labels }}
    labels:
{{ toYaml $pool.labels | indent 6 }}
{{- end }}
{{- if $pool.acceleratorOptions }}
    acceleratorOptions:
{{ toYaml $pool.acceleratorOptions | indent 6 }}
{{- end }}
{{- end }}
  releaseChannel:
    channel: UNSPECIFIED
{{- end }}
{{- end }}
