export SCRIPTS_DIR=$( readlink -e $(dirname $0))
export OUTPUT_DIR=/tmp/dga-factory
export SECRETS_DIR=$( readlink -e ${SCRIPTS_DIR:?}/../secrets)
export USERS_YAML=$( readlink -e ${SCRIPTS_DIR:?}/../users.yaml)
export GDCH_CHARTS_DIR=$( readlink -e ${SCRIPTS_DIR:?}/../../../charts)
export CHARTS_DIR=$( readlink -e ${SCRIPTS_DIR:?}/../charts)
export HELM_CLI=$( readlink -e ${SCRIPTS_DIR:?}/../../../tools/helm_cli/helm_cli.py)
export ORG_NAME="org-15357"
export IAC_PROJECT="iac-root"
export IAC_SA="iac001-sa"
export IAC_SA_FQN="system:serviceaccount:${IAC_PROJECT:?}:${IAC_SA:?}"
export GDCH_ZONE="lux-central1-b"
export GDCH_DOMAIN="lux.clr"
export GDCH_CONSOLE="console.${ORG_NAME}.${GDCH_ZONE}.${GDCH_DOMAIN}"
export CLUSTER_NAME="clstr-20260224"
export KUBECONFIG_PATH="/mnt/c/temp/DGA/cert/"
export GLOBAL_API_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-global-api.kubeconfig
export ZONE_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-${GDCH_ZONE:?}.kubeconfig
export USER_CLUSTER_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA}-${GDCH_ZONE:?}-${CLUSTER_NAME:?}.kubeconfig
export NB_JUPYTER_IMAGE="gcr.io/private-cloud-staging/notebooks/deeplearning-platform-release/tf2-gpu:m125"
export S3_PROXY_IMAGE="data-ets-mhs-data-ets-infra.org-70033.lux-central1-a.lux.clr/dga/lu/etat/ci/ets/platform/ops/s3-proxy@sha256:7eff03cd821638cde5f1fa8d02c130471451c23b69069e3384a81eb235bcbd02"
export S3_PROXY_ENABLED=0
