export SCRIPTS_DIR=$( readlink -e $(dirname "${BASH_SOURCE[0]}"))
export OUTPUT_DIR=${SCRIPTS_DIR:?}/../generated/output
export SECRETS_DIR=${SCRIPTS_DIR:?}/../generated/secrets
export USERS_YAML=${SCRIPTS_DIR:?}/../users.yaml
export GDCH_CHARTS_DIR=${SCRIPTS_DIR:?}/../../../charts
export CHARTS_DIR=${SCRIPTS_DIR:?}/../charts
export HELM_CLI=${SCRIPTS_DIR:?}/../../../tools/helm_cli/helm_cli.py
# Org specific variables
export ORG_NAME="org-15357"
export GDCH_ZONE="lux-central1-b"
export GDCH_DOMAIN="lux.clr"
export IAC_PROJECT="iac-root"
export IAC_SA="iac001-sa"
export IAC_SA_FQN="system:serviceaccount:${IAC_PROJECT:?}:${IAC_SA:?}"
export GDCH_CONSOLE="console.${ORG_NAME}.${GDCH_ZONE}.${GDCH_DOMAIN}"
export CLUSTER_NAME="clstr-20260224"
export KUBECONFIG_PATH=${SCRIPTS_DIR:?}/../generated/kubeconfig
export GLOBAL_API_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-global-api.kubeconfig
export ZONE_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-${GDCH_ZONE:?}.kubeconfig
export USER_CLUSTER_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA}-${GDCH_ZONE:?}-${CLUSTER_NAME:?}.kubeconfig
export NB_JUPYTER_IMAGE="gcr.io/private-cloud-staging/notebooks/deeplearning-platform-release/base-cpu:m125_ext"
export S3_PROXY_IMAGE="data-ets-shr-mhs-data-ets-infra.org-15357.lux-central1-b.lux.clr/dga/s3-proxy:2.0"
export AIS_PREFIX="gdch-infra-operator-"
export S3_PROXY_ENABLED=1
export CLUSTER_K8S_VERSION="1.29.12-gke.800"
export CLUSTER_POD_CIDR_SIZE=18
export CLUSTER_SERVICE_CIDR_SIZE=20
export CLUSTER_INGRESS_SERVICE_IP_SIZE=20
export CLUSTER_MACHINE_TYPE="n3-standard-16-gdc"
export CLUSTER_NODE_COUNT=5
export CLUSTER_NODE_POOL_NAME="pool-20260224"
export CLOUD_BILLING_CONFIG_ACCOUNT_ID="Organization Billing Account"
export HARBOR_ADMIN_EMAIL="sdobrica-sa@opscenter.local"

