export SCRIPTS_DIR=$( readlink -e $(dirname "${BASH_SOURCE[0]}"))
export OUTPUT_DIR=${SCRIPTS_DIR:?}/../generated/output
export SECRETS_DIR=${SCRIPTS_DIR:?}/../generated/secrets
export USERS_YAML=${SCRIPTS_DIR:?}/../users.yaml
export GDCH_CHARTS_DIR=${SCRIPTS_DIR:?}/../../../charts
export CHARTS_DIR=${SCRIPTS_DIR:?}/../charts
export HELM_CLI=${SCRIPTS_DIR:?}/../../../tools/helm_cli/helm_cli.py
# Org specific variables
export ORG_NAME="gdchservices"
export GDCH_ZONE="us-east67-b"
export GDCH_DOMAIN="google.gdch.test"
export IAC_PROJECT="iac-root"
export IAC_SA="iac001-sa"
export IAC_SA_FQN="system:serviceaccount:${IAC_PROJECT:?}:${IAC_SA:?}"
export GDCH_CONSOLE="console.${ORG_NAME}.${GDCH_ZONE}.${GDCH_DOMAIN}"
export CLUSTER_NAME="stress-test"
export KUBECONFIG_PATH=${SCRIPTS_DIR:?}/../generated/kubeconfig
export GLOBAL_API_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-global-api.kubeconfig
export ZONE_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA:?}-${GDCH_ZONE:?}.kubeconfig
export USER_CLUSTER_KUBECONFIG=${KUBECONFIG_PATH:?}/${IAC_PROJECT:?}-${IAC_SA}-${GDCH_ZONE:?}-${CLUSTER_NAME:?}.kubeconfig
export NB_JUPYTER_IMAGE="gcr.io/private-cloud-staging/notebooks/deeplearning-platform-release/tf2-gpu:m125"
export S3_PROXY_IMAGE="data-ets-mhs-574-data-ets-574.${ORG_NAME}.${GDCH_ZONE}.${GDCH_DOMAIN}/dga/s3-proxy:0.0.3"
export AIS_PREFIX="fop-"
export S3_PROXY_ENABLED="no"
export CLUSTER_K8S_VERSION="1.30.12-gke.300"
export CLUSTER_POD_CIDR_SIZE=21
export CLUSTER_SERVICE_CIDR_SIZE=23
export CLUSTER_INGRESS_SERVICE_IP_SIZE=20
export CLUSTER_MACHINE_TYPE="n3-standard-4-gdc"
export CLUSTER_NODE_COUNT=3
export CLUSTER_NODE_POOL_NAME="dga-ets-standard"
export HARBOR_ADMIN_EMAIL="hbadmin@example.com"
export COPY_JOB_IMAGE="data-ets-mhs-574-data-ets-574.${ORG_NAME}.${GDCH_ZONE}.${GDCH_DOMAIN}/dga/alpine:latest"
export BACKUP_BUCKETS_READY="no"
export BACKUP_REPOS_READY="no"

