# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.roleBindings }}
{{- range $binding := .Values.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ required "A binding name is required" $binding.name | quote }}
  namespace: {{ required "A namespace is required for RoleBinding" $binding.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ default "Role" $binding.roleKind | quote }}
  name: {{ required "A roleName is required" $binding.roleName | quote }}
subjects:
{{ toYaml $binding.subjects | indent 2 }}
{{- end }}
{{- end }}

{{- if .Values.clusterRoleBindings }}
{{- range $binding := .Values.clusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required "A binding name is required" $binding.name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ required "A roleName is required" $binding.roleName | quote }}
subjects:
{{ toYaml $binding.subjects | indent 2 }}
{{- end }}
{{- end }}
