{{- if .Values.projectserviceaccounts }}
{{- range $sa := .Values.projectserviceaccounts }}
---
apiVersion: resourcemanager.global.gdc.goog/v1
kind: ProjectServiceAccount
metadata:
  name: {{ required "ProjectServiceAccount name is required" $sa.name | quote }}
  namespace: {{ required "ProjectServiceAccount namespace is required" $sa.namespace | quote }}
{{- end }}
{{- end }}
