# yaml-language-server: $schema=values.schema.json

# GDC Projects ServiceAccounts Configuration
# Create a list of project level serviceaccounts. The vairable name defines the project where service accounts are to be created.
# name: {}
# projectserviceaccounts: {}
  # - "lotus-frontend-sa"
  # - "lotus-backend-sa"
  # - "lotus-db-admin-sa"
