# Default values for gdc-intra-project-network-policies.

# The project/namespace where policies will be applied
project: ""

# Intra-project network policies configuration
# See: https://cloud.google.com/distributed-cloud/hosted/docs/latest/gdch/platform/pa-user/pnp/intra-project-traffic
intraProjectPolicies: []
  # Example Project-level Ingress Policy:
  # - name: base-policy-allow-intra-project-traffic
  #   policyType: Ingress
  #   ingress:
  #     - from:
  #       - projectSelector:
  #           projects:
  #             matchNames:
  #             - "my-project" # Usually the same as .Values.project

  # Example Workload-level Ingress Policy:
  # - name: allow-frontend-to-backend
  #   policyType: Ingress
  #   subject:
  #     subjectType: UserWorkload
  #     matchLabels:
  #       app: backend
  #   ingress:
  #     - from:
  #       - projectSelector:
  #           projects:
  #             matchNames:
  #             - "my-project"
  #           matchLabels:
  #             app: frontend

  # Example Egress Policy:
  # - name: allow-intra-project-outbound-traffic
  #   policyType: Egress
  #   egress:
  #     - to:
  #       - projectSelector:
  #           projects:
  #             matchNames:
  #             - "my-project"
