{{- if .Values.global.projects }}
{{- range $key, $value := .Values.global.projects }}
{{- if $value.projectserviceaccounts }}
{{- range $v := $value.projectserviceaccounts }}
---
apiVersion: resourcemanager.global.gdc.goog/v1
kind: ProjectServiceAccount
metadata:
  name: {{ $v | quote }}
  namespace: {{ $value.name | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}