apiVersion: v2
name: gdc-vm
description: A Helm chart for managing Virtual Machines on GDC version 1.11+
version: 0.1.2
keywords:
  - gdc
  - virtual-machine
  - vm
  - gvm
  - v1.9
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png