{{- if .Values.iamrolebindings }}
{{- $ns := .Values.namespace }}
{{- range $_, $iamrolebinding := .Values.iamrolebindings }}
---
apiVersion: iam.global.gdc.goog/v1
kind: IAMRoleBinding
metadata:
  name: {{ regexReplaceAll "\\W+" (required "A valid subject_name is required" $iamrolebinding.subject_name) "-" | lower }}--{{ regexReplaceAll "\\W+" (required "A valid role is required" $iamrolebinding.role) "-" }}
  namespace: {{ $ns | quote }}
spec:
  roleRef:
    apiGroup: iam.global.gdc.goog/v1
    kind: IAMRole
    name: {{ $iamrolebinding.role | quote }}
  subjects:
  - {{- if ne $iamrolebinding.subject_kind "ServiceAccount" }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
    kind: {{ $iamrolebinding.subject_kind | quote }}
    name: {{ $iamrolebinding.subject_name | quote }}
    {{- if eq $iamrolebinding.subject_kind "ServiceAccount" }}
    namespace: {{ required "subject_namespace is required for ServiceAccount kind" $iamrolebinding.subject_namespace | quote }}
    {{- end }}
{{- end }}
{{- end }}

