# Chart paths relative to the ao-repo root
gdc_vm_chart_path: "../../charts/gdc-vms"
gdc_context_global: # insert API context here

bundle:
  name: ao1-project1-workloads
  privileged: false

gdc_tenants:
  ao1-tenant:
    projects:
      - name: "ao1-project1"
        vms:
          - name: "web-server-01"
            machine_type: "n1-standard-4"
            image: "projects/gdch-system/images/ubuntu-2204"
            boot_disk_size_gb: 50
          - name: "web-server-02"
            machine_type: "n1-standard-4"
            image: "projects/gdch-system/images/ubuntu-2204"
            boot_disk_size_gb: 50
