apiVersion: v2
name: gdc-project-network-policies
description: A Helm chart for Google Distributed Cloud organization management
type: application
version: 0.1.1
appVersion: "1.14.6"
maintainers:
  - name: gdc-iac
