# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# yaml-language-server: $schema=values.schema.json

# The target namespace for these network policies
namespace: ""

# GDC Project Network Policies Configuration
projectnetworkpolicies: []
#  - name: "allow-all-ingress-example"
#    ingress:
#      - {} # Empty object creates an allow-all rule
#
#  - name: "allow-external-ip-example"
#    ingress:
#      - from:
#        - ip_block:
#            cidr: "192.168.1.0/24"
#
#  - name: "allow-cross-project-to-managed-service"
#    subject:
#      subject_type: ManagedService
#      managed_services:
#        match_types:
#        - 'mhs'
#    ingress:
#      - from:
#        - project_selector:
#            projects:
#              match_names:
#              - "d2-ets-user-1"
