apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        pool: cpu
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/test-project/blueprint-images/p10-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: test-project
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer # Or ClusterIP with Ingress
