nb_project: "my-notebook-project"
ro_bucket_name: "data-ets-001-s3-ro-1"
rw_bucket_name: "data-ets-001-s3-rw-1"
tools_bucket_name: "data-ets-001-s3-tools-1"
ro_bucket_fqn: "ro-bucket-fqn"
rw_bucket_fqn: "rw-bucket-fqn"
tools_bucket_fqn: "tools-bucket-fqn"
s3endpoint: "s3.example.com"
aws_access_key_id: "access-key"
aws_secret_access_key: "secret-key"
nb_name: "my-notebook"
nb_conf_image: "alpine:latest"
