{{/* templates/secret.yaml */}}

{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.base64EncodedPassword }}
{{- fail "You must provide a value for postgresql.base64EncodedPassword when postgresql.enabled is true." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pw-{{ .Values.postgresql.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gdch-dbs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    dbtype: postgresql
type: Opaque
data:
  # The key must match the DBCluster name
  {{ .Values.postgresql.clusterName }}: {{ .Values.postgresql.base64EncodedPassword | quote }}
{{- end }}

{{- if .Values.oracle.enabled }}
{{- if not .Values.oracle.base64EncodedPassword }}
{{- fail "You must provide a value for oracle.base64EncodedPassword when oracle.enabled is true." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pw-{{ .Values.oracle.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gdch-dbs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    dbtype: oracle
type: Opaque
data:
  # The key must match the DBCluster name
  {{ .Values.oracle.clusterName }}: {{ .Values.oracle.base64EncodedPassword | quote }}
{{- end }}

{{- if .Values.alloydbomni.enabled }}
{{- if not .Values.alloydbomni.base64EncodedPassword }}
{{- fail "You must provide a value for alloydbomni.base64EncodedPassword when alloydbomni.enabled is true." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pw-{{ .Values.alloydbomni.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gdch-dbs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    dbtype: alloydbomni
type: Opaque
data:
  # The key must match the DBCluster name
  {{ .Values.alloydbomni.clusterName }}: {{ .Values.alloydbomni.base64EncodedPassword | quote }}
{{- end }}

