apiVersion: batch/v1
kind: Job
metadata:
  name: config-copy-{{ .Values.nb_name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      volumes:
        - name: tgt
          persistentVolumeClaim:
            claimName: {{ .Values.nb_name }}-s3-proxy-config
        - name: src
          secret:
            secretName: {{ .Values.nb_project }}-secret
      containers:
        - name: alpine
          image: {{ .Values.nb_conf_image }}
          command:
            - find 
            - /src 
            - -type 
            - f 
            - -exec 
            - cp 
            - -v
            - "{}" 
            - /tgt 
            - ";"
          volumeMounts:
            - name: tgt
              mountPath: /tgt
            - name: src
              mountPath: /src
      restartPolicy: Never
