{{- if .Values.projectserviceaccounts }}
{{- range $saName := .Values.projectserviceaccounts }}
---
apiVersion: resourcemanager.global.gdc.goog/v1
kind: ProjectServiceAccount
metadata:
  name: {{ $saName | quote }}
  # USE $.Values to access the root scope from inside the loop
  namespace: {{ $.Values.name | quote }}
{{- end }}
{{- end }}
