{{- if .Values.iamrolebindings }}
{{- range $_, $iamrolebinding := .Values.iamrolebindings }}
---
apiVersion: iam.global.gdc.goog/v1
kind: IAMRoleBinding
metadata:
  name: {{ regexReplaceAll "\\W+" $iamrolebinding.subject_name "-" }}--{{ regexReplaceAll "\\W+" $iamrolebinding.role "-" }}
  namespace: {{ $iamrolebinding.namespace | quote }}
spec:
  roleRef:
    apiGroup: iam.global.gdc.goog/v1
    kind: IAMRole
    name: {{ $iamrolebinding.role | quote }}
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: {{ default "User" $iamrolebinding.subject_kind | quote }}
    name: {{ $iamrolebinding.subject_name | quote }}
{{- end }}
{{- end }}