{
 "title": "VM Resource Consumption Per Project",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(compute_instance_cpu_usage, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU allocated and usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cpu) (compute_instance_cpu_usage{namespace=~\"$project\"})",
     "legendFormat": "allocated vCPU"
    },
    {
     "expr": "(sum by (cpu) (rate(compute_instance_cpu_usage{state=\"running\", namespace=~\"$project\"}[2m])))",
     "legendFormat": "consumed vCPU"
    }
   ]
  },
  {
   "title": "Allocation per VM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cpu, name) (compute_instance_cpu_usage{namespace=~\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage per VM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (cpu, name) (rate(compute_instance_cpu_usage{state=\"running\", namespace=~\"$project\"}[2m])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory allocated and consumed ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (compute_instance_memory_available_bytes{namespace=\"$project\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(compute_instance_memory_available_bytes{namespace=\"$project\"}-compute_instance_memory_usable_bytes{namespace=\"$project\"})",
     "legendFormat": "consumed"
    }
   ]
  },
  {
   "title": "Memory allocated per VM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (compute_instance_memory_available_bytes{namespace=\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory consumed per VM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (compute_instance_memory_available_bytes{namespace=\"$project\"}-compute_instance_memory_usable_bytes{namespace=\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Disk allocated and consumed ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (compute_instance_disk_bytes_allocated{namespace=\"$project\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum (compute_instance_disk_bytes_used{namespace=\"$project\"})",
     "legendFormat": "consumed"
    }
   ]
  },
  {
   "title": "Allocation per VM Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (compute_instance_disk_bytes_allocated{namespace=\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumption per VM Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (compute_instance_disk_bytes_used{namespace=\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Network Bandwith Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by (network) (rate(compute_instance_network_received_bytes_count{namespace=\"$project\"}[2m])))",
     "legendFormat": "Receive - {{network}}"
    },
    {
     "expr": "(sum by (network) (rate(compute_instance_network_sent_bytes_count{namespace=\"$project\"}[2m])))",
     "legendFormat": "Transmit - {{network}}"
    }
   ]
  },
  {
   "title": "Received bytes per VM per interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by (network, name) (rate(compute_instance_network_received_bytes_count{namespace=~\"$project\"}[2m])))",
     "legendFormat": "{{name}} - {{network}}"
    }
   ]
  },
  {
   "title": "Transmit bytes per VM per interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by (network, name) (rate(compute_instance_network_sent_bytes_count{namespace=~\"$project\"}[2m])))",
     "legendFormat": "{{name}} - {{network}}"
    }
   ]
  }
 ]
}