apiVersion: v2
name: gdc-iam-role-bindings
description: A Helm chart for Google Distributed Cloud organization management
type: application
version: 0.1.2
appVersion: "1.14.6"
maintainers:
  - name: gdc-iac
