# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $plans := ($.Values.backupplans | default dict).cluster | default dict }}
{{- range $i, $plan := $plans }}
---
apiVersion: backup.gdc.goog/v1
kind: ClusterBackupPlan
metadata:
  name: {{ required "A valid backup plan name is required" $plan.name }}
  namespace: {{ $plan.namespace | default ($.Values.backupplans | default dict).namespace | required "A valid namespace is required" }}
spec:
  targetCluster:
    targetClusterType: {{ required "targetClusterType is required" $plan.targetCluster.targetClusterType }}
    targetClusterName:
      kind: {{ $plan.targetCluster.targetClusterName.kind | default "Cluster" | quote }}
      name: {{ required "targetClusterName sequence name is required" $plan.targetCluster.targetClusterName.name }}
  backupSchedule:
    cronSchedule: {{ required "cronSchedule is required" $plan.cronSchedule | quote }}
    paused: {{ $plan.paused | default false }}
  clusterBackupConfig:
    backupScope:
      {{- if $plan.backupScope }}
      {{- toYaml $plan.backupScope | nindent 6 }}
      {{- else }}
      allNamespaces: true
      {{- end }}
    clusterBackupRepositoryName: {{ required "clusterBackupRepositoryName is required" $plan.clusterBackupRepositoryName }}
  {{- if $plan.description }}
  description: {{ $plan.description | quote }}
  {{- end }}
  {{- if $plan.retentionPolicy }}
  retentionPolicy:
    backupDeleteLockDays: {{ if hasKey $plan.retentionPolicy "backupDeleteLockDays" }}{{ $plan.retentionPolicy.backupDeleteLockDays }}{{ else }}0{{ end }}
    backupRetainDays: {{ if hasKey $plan.retentionPolicy "backupRetainDays" }}{{ $plan.retentionPolicy.backupRetainDays }}{{ else }}0{{ end }}
  {{- end }}
{{- end }}
