# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $plans := ($.Values.backupplans | default dict).vm | default dict }}
{{- range $i, $plan := $plans }}
---
apiVersion: virtualmachine.gdc.goog/v1
kind: VirtualMachineBackupPlanTemplate
metadata:
  name: {{ printf "%s-template" $plan.name | quote }}
  namespace: {{ $plan.namespace | default ($.Values.backupplans | default dict).namespace | required "A valid namespace is required" }}
spec:
  backupRepository: {{ required "backupRepository is required" $plan.backupRepository | quote }}
---
apiVersion: virtualmachine.gdc.goog/v1
kind: VirtualMachineBackupPlan
metadata:
  name: {{ required "A valid backup plan name is required" $plan.name }}
  namespace: {{ $plan.namespace | default ($.Values.backupplans | default dict).namespace | required "A valid namespace is required" }}
spec:
  virtualMachineBackupPlanTemplate: {{ printf "%s-template" $plan.name | quote }}
  backupConfig:
    backupScope:
      {{- if $plan.backupScope }}
      {{- toYaml $plan.backupScope | nindent 6 }}
      {{- else }}
      {}
      {{- end }}
    volumeStrategy: {{ required "volumeStrategy is required (ProvisionerSpecific or LocalSnapshotOnly)" $plan.volumeStrategy }}
  backupSchedule:
    cronSchedule: {{ required "cronSchedule is required" $plan.cronSchedule | quote }}
    paused: {{ $plan.paused | default false }}
{{- end }}
