iac:
  subject_name: "fop-iac001@example.com"
global:
  iamrolebindings:
    - role: "project-creator"
      subject_kind: "User"
      subject_name: "fop-user001@example.com"
  projects:
    - name: "project1"
      iamrolebindings: 
      - role: "namespace-admin"
        subject_kind: "User"
        subject_name: "fop-user001@example.com"
      - role: "project-bucket-admin"
        subject_kind: "User"
        subject_name: "fop-user001@example.com"
      - role: "project-bucket-object-admin"
        subject_kind: "User"
        subject_name: "fop-user001@example.com"
      - role: "project-bucket-object-admin"
        subject_kind: "User"
        subject_name: "system:serviceaccount:helmfile1:samplesa"
      projectserviceaccounts:
      - samplesa1