# Default values for gdc-standard-cluster-baseline-netpols.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The namespace where these baseline policies will be applied
namespace: default

defaultDeny:
  # Enable the default deny-all policy for the namespace
  enabled: true

allowDns:
  # Enable explicit egress to kube-dns
  enabled: true

allowAll:
  # Enable an overriding policy that allows all traffic (use with extreme caution, e.g. for bridging to shared clusters securely)
  enabled: false
