{{- if .Values.billingaccounts }}
{{- range $_, $acc := .Values.billingaccounts }}
---
apiVersion: billing.global.gdc.goog/v1
kind: BillingAccount
metadata:
  name: {{ $acc.name | required "name is required" }}
  namespace: platform
  annotations:
    helm.sh/resource-policy: keep
spec:
  displayName: {{ $acc.display_name | required "display_name is required" }}
  paymentSystemConfig:
    cloudBillingConfig:
      accountID: {{ $acc.cloud_billing_config_account_id | required "cloud_billing_config_account_id is required" }}
{{- end }}
{{- end }}
