apiVersion: networking.global.gdc.goog/v1
kind: {{ eq .Values.loadBalancingScheme "EXTERNAL" | ternary "ForwardingRuleExternal" "ForwardingRuleInternal" }}
metadata:
  namespace: {{ required "A valid namespace is required (.Values.namespace)" .Values.namespace | quote }}
  name: {{ required "A valid name is required (.Values.name)" .Values.name | quote }}
spec:
  {{- if .Values.forwardingRule.cidrName }}
  cidrRef:
    name: {{ .Values.forwardingRule.cidrName | quote }}
  {{- end }}
  ports:
  - port: {{ required "A valid forwardingRule port is required (.Values.forwardingRule.port)" .Values.forwardingRule.port }}
    protocol: {{ required "A valid forwardingRule protocol is required (.Values.forwardingRule.protocol)" .Values.forwardingRule.protocol | quote }}
  backendServiceRef:
    name: {{ printf "%s-backendservice" (required "A valid name is required (.Values.name)" .Values.name) | quote }}
