apiVersion: postgresql.dbadmin.gdc.goog/v1
kind: DBCluster
metadata:
  name: keycloak-db
  namespace: my-gdc-project
spec:
  version: POSTGRESQL_14
  availabilityType: ZONAL_HA
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
  storage:
    size: "100Gi"
