# Default values for gdc-backup-plans.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application: []
#  - name: "majduk-backup-plan"
#    namespace: "data-ets-shared-infra"
#    clusterName: "stress-test"
#    backupRepository: "billing-cluster-backup-repository"
#    backupScope:
#      allNamespaces: true
#    includeSecrets: true
#    includeVolumeData: true
#    cronSchedule: "35 20 * * *"
#    paused: false
#    deactivated: false
#    retentionPolicy:
#      backupDeleteLockDays: 0
#      backupRetainDays: 0
#      locked: false
#      numBackupsToRetain: 0

cluster: []
#  - name: my-cluster-backup-plan
#    namespace: project-namespace
#    targetCluster:
#      targetClusterType: UserCluster
#      targetClusterName:
#        kind: "Cluster"
#        name: "my-user-cluster"
#    cronSchedule: "0 2 * * *"
#    paused: false
#    clusterBackupRepositoryName: my-cluster-repo
#    backupScope:
#      allNamespaces: true
#    retentionPolicy:
#      backupDeleteLockDays: 0
#      backupRetainDays: 10
#    description: "Daily cluster backup"

harbor: []
#  - name: my-harbor-backup-plan
#    namespace: harbor-namespace
#    harborInstance: my-harbor-instance
#    backupRepository: my-harbor-repo
#    cronSchedule: "0 3 * * *"
#    paused: false
#    retentionPolicy:
#      backupRetainDays: 14
#    description: "Daily harbor backup"

vm: []
#  - name: my-vm-backup-plan
#    namespace: project-namespace
#    backupRepository: my-vm-repo
#    cronSchedule: "0 1 * * *"
#    paused: false
#    volumeStrategy: ProvisionerSpecific
#    backupScope:
#      vmResourceLabelSelector:
#        backup: daily
#     # OR
#     # selectedVirtualMachines:
#     #   - resourceName: vm-1
#     # selectedVirtualMachineDisks:
#     #   - resourceName: disk-1
