apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ required "namespace is required" .Values.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.dbName }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
          name: dbport
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.user }}", "-d", "{{ .Values.postgres.dbName }}"]
          initialDelaySeconds: 5
          periodSeconds: 5
