apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ required "namespace is required" .Values.namespace }}
  labels:
    app: {{ .Values.web.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
    protocol: TCP
  selector:
    app: {{ .Values.web.name }}
