# yaml-language-server: $schema=values.schema.json

# GDC Projects Configuration
# Represents a namespace that spans across multiple user clusters in an organization. Define projects to be created
projects: {}
  # Example project configuration:
  # project1:
  #   # Required: Name of the GDC project
  #   name: "project-x"
  #   # Required: Namespace of the project (options: "platform" or "gpc-system")
  #   namespace: "platform"
