apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nb_project }}-secret
  namespace: {{ .Values.nb_project }}
type: Opaque
stringData:
  config.yaml: |
    targets:
      ro-bucket:
        mount:
          path:
            - /{{ .Values.ro_bucket_name }}/
        actions:
          head:
            enabled: true
          get:
            enabled: true
        bucket:
          name: {{ .Values.ro_bucket_fqn }}
          prefix:
          region:
          s3Endpoint: {{ .Values.s3endpoint }}
          disableSSL: false
          credentials:
             accessKey:
               value: {{ .Values.aws_access_key_id }}
             secretKey:
               value: {{ .Values.aws_secret_access_key }}
      rw-bucket:
        mount:
          path:
            - /{{ .Values.rw_bucket_name }}/
        actions:
          head:
            enabled: true
          get:
            enabled: true
          put:
            enabled: true
          delete:
            enabled: true
        bucket:
          name: {{ .Values.rw_bucket_fqn }}
          prefix:
          region:
          s3Endpoint: {{ .Values.s3endpoint }}
          disableSSL: false
          credentials:
             accessKey:
               value: {{ .Values.aws_access_key_id }}
             secretKey:
               value: {{ .Values.aws_secret_access_key }}
      tools-bucket:
        mount:
          path:
            - /{{ .Values.tools_bucket_name }}/
        actions:
          head:
            enabled: true
          get:
            enabled: true
        bucket:
          name: {{ .Values.tools_bucket_fqn }}
          prefix:
          region:
          s3Endpoint: {{ .Values.s3endpoint }}
          disableSSL: false
          credentials:
             accessKey:
               value: {{ .Values.aws_access_key_id }}
             secretKey:
               value: {{ .Values.aws_secret_access_key }}
