apiVersion: v1
kind: Secret
metadata:
  name: db-ro-creds
  namespace: test-project # kpt-set: ${namespace}
type: Opaque
stringData:
  username: "postgres" # Replace with actual username if different
  password: "password" # Replace with actual password
  host: "postgres-db" # Service name of the DBCluster
