{{- if .Values.iamroles }}
{{- range $_, $role := .Values.iamroles }}
---
apiVersion: iam.global.gdc.goog/v1
kind: CustomRole
metadata:
  name: {{ $role.name | quote }}
  namespace: platform
spec:
  metadata:
    id: {{ $role.name | quote }}
    title: {{ $role.title | quote }}
    description: {{ $role.description | quote }}
    stage: {{ $role.stage | quote }}
    scope: {{ default "organization" $role.scope | quote }}
    roleNamespaces:
    {{- range $ns := $role.roleNamespaces }}
      - {{ $ns }}
    {{- end }} 
  {{- if $role.globalRules }}
  globalRules:  
   {{ $role.globalRules | toYaml | replace "|" "" | indent 4 }}
   {{- end }}
   {{- if $role.zonalRules }}
  zonalRules:
   {{ $role.zonalRules | toYaml | replace "|" "" | indent 4 }}
   {{- end }}
{{- end }}
{{- end }}
