# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.name }}
apiVersion: networking.global.gdc.goog/v1
kind: BackendService
metadata:
  namespace: {{ required "A valid namespace is required (.Values.namespace)" .Values.namespace | quote }}
  name: {{ printf "%s-backendservice" (required "A valid name is required (.Values.name)" .Values.name) | quote }}
spec:
  backendRefs:
  - name: {{ printf "%s-backend" (required "A valid name is required (.Values.name)" .Values.name) | quote }}
    zone: {{ required "A valid backend zone is required (.Values.backendService.zone)" .Values.backendService.zone | quote }}
  {{- if .Values.healthCheck.enabled }}
  healthCheckName: {{ printf "%s-healthcheck" .Values.name | quote }}
  {{- end }}
  targetPorts:
  - port: {{ required "A valid backendService port is required (.Values.backendService.port)" .Values.backendService.port }}
    protocol: {{ required "A valid backendService protocol is required (.Values.backendService.protocol)" .Values.backendService.protocol | quote }}
    targetPort: {{ required "A valid backendService targetPort is required (.Values.backendService.targetPort)" .Values.backendService.targetPort }}

{{- end }}
