{{- if .Values.projects }}
{{- range $key, $value := .Values.projects }}
---
apiVersion: {{ if $.Capabilities.APIVersions.Has "resourcemanager.gdc.goog/v1" -}}
resourcemanager.gdc.goog/v1
{{- else -}}
resourcemanager.gdc.goog/v1alpha1
{{- end }}
kind: Project
metadata:
  name: {{ required "A valid .name is required for each project" $value.name | quote }}
  namespace: "platform"
{{- if .projectserviceaccounts }}
{{- range $k := .projectserviceaccounts }}
---
apiVersion: resourcemanager.gdc.goog/v1
kind: ProjectServiceAccount
metadata:
  name: {{ $k | quote }}
  namespace: {{ $value.name | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}