# core-tenants.yaml

# Org-level configurations and global chart paths/contexts

gdc_org_network_policies_chart_path: "../charts/gdc-org-network-policies"
gdc_org_policies_chart_path: "../charts/gdc-org-policies"
gdc_context_global: # the global API context for org-level configs

# the below is example config for illustration purposes
core_config:
  gdc_tenants:
    pa-tenant:
      global:
        org_network_policies:
          - name: "allow-vertex-ai-access"
            subject:
            services:
              match_types:
                - "ai"
            ingress:
              - from:
                  - ip_block:
                      cidr: "10.0.0.0/8"
        org_policies:
          - name: "no-update-to-marketplace-service"
            apiGroup: "marketplace.gdc.goog"
            kind: "MarketplaceService"
            disabledOperations:
              - "UPDATE"
