# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $repos := ($.Values.backuprepositories | default dict).vm | default dict }}
{{- range $i, $repo := $repos }}
---
apiVersion: backup.gdc.goog/v1
kind: BackupRepository
metadata:
  name: {{ required "A valid repository name is required" $repo.name }}
  namespace: {{ $repo.namespace | default ($.Values.backuprepositories | default dict).namespace | required "A valid repository namespace is required" }}
spec:
  secretReference:
    namespace: {{ $repo.secretReference.namespace | default $repo.namespace | default ($.Values.backuprepositories | default dict).namespace | required "Secret namespace required" }}
    name: {{ required "A valid secret name is required under secretReference.name" $repo.secretReference.name }}
  endpoint: {{ required "A valid endpoint is required" $repo.endpoint }}
  type: {{ $repo.type | default "S3" | quote }}
  {{- if eq ($repo.type | default "S3") "S3" }}
  s3Options:
    bucket: {{ required "A valid bucket FQDN is required under s3Options.bucket" $repo.s3Options.bucket }}
    region: {{ required "A valid region is required under s3Options.region" $repo.s3Options.region }}
    forcePathStyle: {{ $repo.s3Options.forcePathStyle | default false }}
  {{- end }}
  importPolicy: {{ $repo.importPolicy | default "ReadWrite" }}
{{- end }}
