# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# yaml-language-server: $schema=values.schema.json

# GDC Clusters Configuration
clusters:
  # Example cluster configuration based on cluster.gdc.goog/v1
  #
  # - name: "user-vm-3"                         # Required: Name of the cluster
  #   namespace: "platform"                     # Required: Namespace in the admin cluster
  #   clusterNetwork:                           # Optional: Networking sizes
  #     podCIDRSize: 21
  #     serviceCIDRSize: 23
  #   initialVersion:
  #     kubernetesVersion: "1.30.12-gke.300"    # Version of GDCH Kubernetes
  #   loadBalancer:
  #     ingressServiceIPSize: 21
  #   nodePools:                                # Optional: Defines node pools to deploy
  #     - name: "worker-node-pool"
  #       machineTypeName: "n3-standard-16-gdc"
  #       nodeCount: 3
  #   releaseChannel: "UNSPECIFIED"
  #   projectBindings:                          # Optional: Binds GDCH projects to this cluster
  #     - "agtest-project"
  #     - "other-project"
