{{- if .Values.model.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-hf-token
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.model.hfToken | quote }}
{{- end }}
