# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Reference: https://github.com/helm/chart-testing-action
name: Linting
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  chart-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.18.0

      - name: Set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.9
          check-latest: true

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          # Note: Also update in scripts/lint.sh
          version: v3.11.0

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Set up Kube Tools (kubeconform & conftest)
        uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            kubeconform
            conftest
          kubeconform: '0.6.7'
          conftest: '0.56.0'

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.1.2

      - name: Run Chart Test Suite (test-charts.sh)
        run: ./scripts/test-charts.sh

      - name: Setup Helmfile
        uses: helmfile/helmfile-action@614b4cd063ada10b87f668f6ffd35485bce0cac5 # v2.4.8
        with:
          helmfile-version: 'v1.2.1'
          helm-version: 'v3.18.0'
          helm-plugins: >-
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: version

      - name: Run Foundations Validation (validate.sh)
        run: ./foundations/scripts/validate.sh dev

      # - name: Run docs-testing (helm-docs)
      #   id: helm-docs
      #   run: |
      #     ./scripts/helm-docs.sh
      #     if [[ $(git diff --stat) != '' ]]; then
      #       echo -e '\033[0;31mDocumentation outdated!\033[0m ❌'
      #       git diff --color
      #       exit 1
      #     else
      #       echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
      #     fi

