apiVersion: v1
kind: Secret
metadata:
  name: db-ro-creds
  namespace: test-project # kpt-set: ${namespace}
type: Opaque
# Values must be base64 encoded: echo -n 'my-password' | base64
data:
  username: cG9zdGdyZXM= # postgres
  password: cGFzc3dvcmQ= # password
  host: cG9zdGdyZXMtc3Zj # postgres-svc
